export const SET_MESSAGE = 'SET_MESSAGE'

export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const LOADING_USER = 'LOADING_USER'

export const SET_TRANSLATOR = 'SET_TRANSLATOR'
export const REMOVE_TRANSLATOR = 'REMOVE_TRANSLATOR'
export const LOADING_TRANSLATOR = 'LOADING_TRANSLATOR'
